CREATE PROC What_DB_is_that 
   @ID INT,
   @NEWID INT = 123 OUT READONLY,
   @NAME VARCHAR(123) = 'ASDASD' OUT,
   @AGE INT,
   @NEWNAME VARCHAR(123) = 'ASDASD' OUT,
AS
SELECT DB_NAME(@ID) AS ThatDB;

CREATE PROC What_DB_is_that2
   @ID INT,
   @NAME VARCHAR(123) = 'ASDASD' OUT,
   @NEWAGE INT,
   @AGE INT,
AS
SELECT DB_NAME(@ID) AS ThatDB;

CREATE PROC What_DB_is_that3
   @ID INT,
   @NAME VARCHAR(123) = 'ASDASD' OUT READONLY,
   @AGE INT READONLY,
AS
SELECT DB_NAME(@ID) AS ThatDB;
