import LocalizedStrings from 'react-localization';
const localization = {
    en: {
        Home: "Home",
        Events: "Events",
        Venues: "Venues",
        Account: "Account",
        SignIn: "Sign in",
        Cart: "Cart",
        ManageEvents: "Manage events",
        ManageUsers: "Manage users",
        ManageVenues: "Manage venues",
        Tools: "Tools",
        SignUpLabel: "Sign up to Events.by",
        username: "username",
        Username: "Username",
        name: "name",
        surname: "surname",
        Name: "Name",
        Surname: "Surname",
        Email: "Email",
        password: "password",
        repeatPassword: "repeat password",
        email: "email",
        signUp: "Sign up",
        BackToHome: "Back to home page",
        SignInLabel: "Sign in to Events.by",
        DontHaveAccount: "Don't have account? Create account",
        SignIn: "Sign in",
        UpcomingEvents: "Upcoming events",
        AccountManagement: "Account management",
        Balance: "Balance",
        MyTickets: "My tickets",
        EditContactInformation: "Edit contact information",
        ChangePassword: "Change password",
        Exit: "Exit",
        CurrentPasswordLabel: "Current password",
        NewPasswordLabel: "New password",
        Submit: "Submit",
        IncorrectEmail: "Incorrect email",
        AllFieldsMustBeFilled: "All fields must be filled",
        ContactInformationChanged: "Contact information successfully changed",
        SomethingWrong: "Something wrong",
        PasswordIsTooEasy: "Password must be at least 6 characters.\nPassword must have at least one non alphanumeric character.\nPassword must have at least one digit('0'- '9').\nPassword must have at least one uppercase('A'- 'Z').\nPassword must have at least one lowercase ('a' - 'z').",
        PasswordsAreNotEqual: "Passwords are not equal",
        Roles: "Roles",
        TimeZone: "Time zone",
        DeleteVenueManager: "Delete VenueManager",
        AddVenueManager: "Add VenueManager",
        DeleteEventManager: "Delete EventManager",
        AddEventManager: "Add EventManager",
        DeleteUser: "Delete User",
        AddUser: "Add User",
        Delete: "Delete",
        Create: "Create",
        UsersManagement: "Users management",
        NoUsers: "There are no users",
        UserCreating: "User creating",
        CouldNotDeleteUser: "Couldn't delete user",
        Description: "Description",
        Start: "Start date and time",
        Finish: "Finish date and time",
        Choose: "Choose image",
        EventCreating: "Event creating",
        Loading: "Loading",
        LayoutForEventMustBeSelected: "Layout for event must be selected",
        Details: "Details",
        ThereNoEvents: "There are no events",
        Edit: "Edit",
        Import: "Import",
        EventsManagement: "Events management",
        SomethingWrongDuringImport: "Something wrong during import",
        EventEditing: "Event editing",
        Browse: "Browse",
        ChangeLayout: "Change layout",
        EventAreas: "Event areas",
        Amount: "Amount",
        SetPrice: "Set price",
        ThereAreNoVenues: "There are no venues",
        Selected: "Selected",
        Select: "Select"
    },
    ru: {
        Home: "Главная",
        Events: "События",
        Venues: "Места проведения",
        Account: "Аккаунт",
        SignIn: "Войти",
        Cart: "Корзина",
        ManageEvents: "Управление событиями",
        ManageUsers: "Управление пользователями",
        ManageVenues: "Управление местами проведения",
        Tools: "Инструменты",
        SignUpLabel: "Регистрация в Events.by",
        username: "логин",
        Username: "Логин",
        name: "имя",
        surname: "фамилия",
        Name: "Имя",
        Surname: "Фамилия",
        Email: "Электронная почта",
        password: "пароль",
        repeatPassword: "повторить пароль",
        email: "адрес электронной почты",
        signUp: "Зарегестрироваться",
        BackToHome: "Вернуться на домашнюю страницу",
        SignInLabel: "Вход в Events.by",
        DontHaveAccount: "Нет аккаунта? Создать аккаунт",
        SignIn: "Войти",
        UpcomingEvents: "Ближайшие события",
        AccountManagement: "Личный кабинет",
        Balance: "Баланс",
        MyTickets: "Мои билеты",
        EditContactInformation: "Редактировать информацию",
        ChangePassword: "Сменить пароль",
        Exit: "Выйти",
        CurrentPasswordLabel: "Текущий пароль",
        NewPasswordLabel: "Новый пароль",
        Submit: "Подтвердить",
        IncorrectEmail: "Неверный адрес электронной почты",
        AllFieldsMustBeFilled: "Все поля должны быть заполнены",
        ContactInformationChanged: "Контактная информация успешно изменена",
        SomethingWrong: "Что-то не так",
        PasswordIsTooEasy: "Пароль должен быть не менее 6 символов.\nПароль должен содержать не менее однго специального символа.\nПароль должен содержать не менее одной цифры('0'- '9').\nПароль должен содержать не менее одного символа верхнего регистра('A'- 'Z').\nПароль должен содержать не менее одного символа нижнего регистра ('a' - 'z').",
        PasswordsAreNotEqual: "Пароли не совпадают",
        Roles: "Роли",
        TimeZone: "Временная зона",
        DeleteVenueManager: "Удалить VenueManager",
        AddVenueManager: "Добавить VenueManager",
        DeleteEventManager: "Удалить EventManager",
        AddEventManager: "Добавить EventManager",
        DeleteUser: "Удалить User",
        AddUser: "Добавить User",
        Delete: "Удалить",
        Create: "Создать",
        UsersManagement: "Управление пользователями",
        NoUsers: "Нет пользователей",
        UserCreating: "Создание пользователя",
        CouldNotDeleteUser: "Не удалось удалить пользователя",
        Description: "Описание",
        Start: "Время и дата начала",
        Finish: "Время и дата окончания",
        Choose: "Выберите изображение",
        EventCreating: "Создание события",
        Loading: "Загрузка",
        LayoutForEventMustBeSelected: "Шаблон для события должен быть выбран",
        Details: "Подробнее",
        ThereNoEvents: "Нет событий",
        Edit: "Редактировать",
        Import: "Импортировать",
        EventsManagement: "Управление событиями",
        SomethingWrongDuringImport: "Что-то пошло не так во время импортирования",
        EventEditing: "Редактирование события",
        Browse: "Выбрать",
        ChangeLayout: "Изменить шаблон",
        EventAreas: "Области события",
        Amount: "Всего",
        SetPrice: "Установить цену",
        ThereAreNoVenues: "Нет мест проведений",
        Selected: "Выбран",
        Select: "Выбрать"
    },
    be: {
        Home: "Галоўная",
        Events: "Падзеі",
        Venues: "Месцы правядзення",
        Account: "Рахунак",
        SignIn: "Увайсці",
        Cart: "Карзіна",
        ManageEvents: "Кіраванне падзеямі",
        ManageUsers: "Кіраванне карыстальнікамі",
        ManageVenues: "Кіраванне месцамі правядзення",
        Tools: "Начынне",
        SignUpLabel: "Рэгістрацыя ў Events.by",
        username: "лагін",
        name: "імя",
        surname: "прозвішча",
        Username: "Лагін",
        Name: "Імя",
        Surname: "Прозвішча",
        password: "пароль",
        repeatPassword: "паўтарыце пароль",
        email: "адрас электроннай пошты",
        Email: "Адрас электроннай пошты",
        signUp: "Зарэгістравацца",
        BackToHome: "Вярнуцца на хатнюю старонку",
        SignInLabel: "Увайсці ў Events.by",
        DontHaveAccount: "Няма рахунку? Зрабите рахунак",
        SignIn: "Аўтарызацыя",
        UpcomingEvents: "Бліжэйшыя падзеі",
        AccountManagement: "Асабісты кабінет",
        Balance: "Баланс",
        MyTickets: "Мае квіткі",
        EditContactInformation: "Рэдагаваць інфармацыю",
        ChangePassword: "Змяніць пароль",
        Exit: "Выйсці",
        CurrentPasswordLabel: "Бягучы пароль",
        NewPasswordLabel: "Новы пароль",
        Submit: "Пацвердзіць",
        IncorrectEmail: "Няправільны адрас электроннай пошты",
        AllFieldsMustBeFilled: "Усе палі павінны быць запоўненыя",
        ContactInformationChanged: "Кантактная інфармацыя паспяхова зменена",
        SomethingWrong: "Нешта не так",
        PasswordIsTooEasy: "Пароль павінен быць не менш за 6 знакаў.\nПароль павінен змяшчаць не менш аднаго спецыяльнага сімвала.\nПароль павінен змяшчаць не менш адной лічбы('0'- '9').\nПароль павінен змяшчаць не менш аднаго знака верхняга рэгістра('A'- 'Z').\nПароль павінен змяшчаць не менш аднаго сімвала ніжняга рэгістра ('a' - 'z').",
        PasswordsAreNotEqual: "Паролі не супадаюць",
        Roles: "Ролі",
        TimeZone: "Часовая зона",
        DeleteVenueManager: "Выдаліць VenueManager",
        AddVenueManager: "Дадаць VenueManager",
        DeleteEventManager: "Выдаліць EventManager",
        AddEventManager: "Дадаць EventManager",
        DeleteUser: "Выдаліць User",
        AddUser: "Дадаць User",
        Delete: "Выдаліць",
        Create: "Стварыць",
        UsersManagement: "Кіраванне карыстальнікамі",
        NoUsers: "Няма карыстальнікаў",
        UserCreating: "Стварэнне карыстальніка",
        CouldNotDeleteUser: "Немагчыма выдаліць карыстальніка",
        Description: "Апісанне",
        Start: "Час і дата пачатку",
        Finish: "Час і дата заканчэння",
        Choose: "Вылучыце малюнак",
        EventCreating: "Стварэнне падзеі",
        Loading: "Загрузка",
        LayoutForEventMustBeSelected: "Шаблон для падзеі павінен быць абраны",
        Details: "Падрабязна",
        ThereNoEvents: "Няма падзей",
        Edit: "Рэдагаваць",
        Import: "Імпартаваць",
        EventsManagement: "Кіраванне падзеямі",
        SomethingWrongDuringImport: "Нешта пайшло не так падчас імпартавання",
        EventEditing: "Рэдагаванне падзеі",
        Browse: "Выбраць",
        ChangeLayout: "Змяніць шаблон",
        EventAreas: "Вобласці падзеі",
        Amount: "Разам",
        SetPrice: "Ўсталяваць цану",
        ThereAreNoVenues: "Няма месцаў правядзення",
        Selected: "Выбраны",
        Select: "Выбраць"
    }
}

let strings = new LocalizedStrings(localization);
let search = window.location.search;
let params = new URLSearchParams(search);
strings.setLanguage(params.get('lang') ?? localStorage.getItem('lang') ?? "en");

export { strings };
