name: scanning-tool
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:
    branches: [ main ]
jobs:
  scan-db-changes:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Clone scanning-tool
        run: |
          eval "$(ssh-agent -s)"
          ssh-add - <<< "${{ secrets.DEPLOY_KEY }}"
          git clone git@github.com:DenisDoroshko/scanning-tool.git scanning-tool
      - name: Build & Run tool
        run: |
          dotnet build "scanning-tool/src/ScanningTool.Console/ScanningTool.Console.csproj" -c Release
          dotnet publish "scanning-tool/src/ScanningTool.Console/ScanningTool.Console.csproj" --no-restore -c Release -o ${{ github.workspace }}/app
          cd ${{ github.workspace }}/app
          ./ScanningTool.Console -o DenisDoroshko -r Test -c $GITHUB_HEAD_REF -d main -t ${{ secrets.GITHUB_TOKEN }}
