name: scanning-tool
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # Stores path to the directory of the current branch from which pull request is created
      GITHUB_CURRENT_PATH: ""
      # Stores path to the directory of the main branch to which pull request is created
      GITHUB_ORIGINAL_PATH: ""
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get original and current state of files
        run: |
          cd ${{ github.workspace }}
          cp -R . ./../current/
          git switch main
          echo "GITHUB_CURRENT_PATH=$(realpath ./../current)" >> $GITHUB_ENV
          echo "GITHUB_ORIGINAL_PATH=$(realpath ./)" >> $GITHUB_ENV
      - name: Clone scanning-tool
        run: |
          eval "$(ssh-agent -s)"
          ssh-add - <<< "${{ secrets.DEPLOY_KEY }}"
          git clone git@github.com:DenisDoroshko/scanning-tool.git scanning-tool
      - name: Build & Run tool
        run: |
          dotnet build "scanning-tool/src/ScanningTool.Console/ScanningTool.Console.csproj" -c Release
          dotnet publish "scanning-tool/src/ScanningTool.Console/ScanningTool.Console.csproj" --no-restore -c Release -o ${{ github.workspace }}/app
          cd ${{ github.workspace }}/app
          ./ScanningTool.Console -o ${{env.GITHUB_ORIGINAL_PATH}} -c ${{env.GITHUB_CURRENT_PATH}} -t ${{ secrets.GITHUB_TOKEN }} -e $GITHUB_EVENT_NAME -d $GITHUB_EVENT_PATH -r ${{ github.workspace }}/../current/.github/scanning-tool-ruleset.json
